---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars:  
    #your region  
    region: us-east-1
  tasks:  
    - name: EC2 basic provisioning  
      ec2:
        region: "{{ region }}"  
        key_name: ansible
        instance_type: t2.micro
        image: ami-42a2532b
        wait: yes    
        #group: sg_webserver_apsydney
        #nstance_tags:
         # group: webserver
        exact_count: 1
        #count_tag:
          #group: webserver
